### ISSUE TITLE
locating the MRtrix3 install 

### ISSUE THREAD

**Issue by jdtournier** [NYU-DiffusionMRI/DESIGNER#8]
A [recent post on our forum](https://community.mrtrix.org/t/using-mrtrix3-with-designer/3700?u=jdtournier) alerted me to the fact that designer uses what I'd consider an error-prone way to locate the MRtrix3 libraries - see my response for further details. 

Would you be open to using MRtrix3's own [module handling solutions](https://mrtrix.readthedocs.io/en/latest/tips_and_tricks/external_modules.html) to deal with these issues? We've had [lots of discussions on the topic](https://github.com/MRtrix3/mrtrix3/pull/1613), it would be good to converge on something that we're all happy to support.

I'm also looping @Lestropie into the conversation, he'll be interested in this.

**Comment by badesar1** [comment]
Thanks for reaching out. I am happy to modify the way designer handles loading the mrtrix3 libraries.  Do you generally prefer that I have users modify their PYTHON_PATH upon installation of designer? This seems to me to be the simplest solution, although I can see in the thread you linked to that a file such as `__locate_mrtrix3.py` would be a more general solution. 

We are currently wrapping up improved denoising and gibbs artifact correction functions and we should be ready to push the update next week. I can include the new way of handling `import mrtrix3` alongside this update.

Ben

**Comment by Lestropie** [comment]
> Do you generally prefer that I have users modify their PYTHON_PATH upon installation of designer?

We generally advise against this (even though I do it all the time myself...). Using the appropriate filesystem structure and creating the softlink to `bin/mrtrix3.py` is the preferred approach.

> although I can see in the thread you linked to that a file such as __locate_mrtrix3.py would be a more general solution.

While the name "`__locate_mrtrix3.py`" was used earlier in that particular discussion, what's done in `bin/mrtrix3.py` and utilised via creating a softlink in the module as described in the online documentation ended up being the final approach.

> I can include the new way of handling import mrtrix3 alongside this update.

Note that you won't be able to make use of this handling without bringing in the Python API overhaul (MRtrix3/mrtrix3#1449). Porting is pretty easy: I've not bothered writing instructions on it because I don't know that there are that many external developers using it, but you can probably infer from the changes to the *MRtrix3* scripts in the linked PR what needs to be changed, and just give me a shout if you get stuck on anything.

**Comment by jdtournier** [comment]
Just to clarify one point that might not have been clear from @Lestropie's earlier post: the Python backend has changed in our latest release, and I don't think it'll be possible to come up with a script that works with both versions >= `3.0.0` _and_ < `3.0_RC3` (@Lestropie: please correct me if I'm wrong here). I would strongly recommend you start using the new version from now, but I appreciate this does mean some users are going to have to update their own installation, which will likely cause some friction. I can't really see a way around this unfortunately... 

Otherwise, I recommend you rely on the [module handling documentation](https://mrtrix.readthedocs.io/en/latest/tips_and_tricks/external_modules.html) only. Most issues are I think fairly well articulated there. If you need more context, or to understand why this particular approach was taken, then the discussion on GitHub would be worth looking at. And of course, we're always happy to help if needed, just give us a shout!

**Comment by badesar1** [comment]
Hi guys,
I modified the designer code to work with the updated mrtrix python backend. I also updated some of the documentation to help explain the new installation step. The directory is structured along to the external module documentation so all users need to do is make a symbolic link to mrtrix3.py.

Thanks for all your help!
